// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTsOGsx-fjmPCjj_5TCXshJQ68NA7foM',
    appId: '1:235654356599:web:8aab28d24a0eedd6d23072',
    messagingSenderId: '235654356599',
    projectId: 'scrappd-4ff5e',
    authDomain: 'scrappd-4ff5e.firebaseapp.com',
    storageBucket: 'scrappd-4ff5e.firebasestorage.app',
    measurementId: 'G-VDRL4BJDLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGZR6MjcaW2VrgC0hWBqR3-_ybnAbAYA',
    appId: '1:235654356599:android:16d8dcebe9dd3f43d23072',
    messagingSenderId: '235654356599',
    projectId: 'scrappd-4ff5e',
    storageBucket: 'scrappd-4ff5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Z_wfPUA7ny9ZoigU5mYi78UXQX3ddn0',
    appId: '1:235654356599:ios:9a533e67e2684a13d23072',
    messagingSenderId: '235654356599',
    projectId: 'scrappd-4ff5e',
    storageBucket: 'scrappd-4ff5e.firebasestorage.app',
    iosBundleId: 'com.example.scrappdMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Z_wfPUA7ny9ZoigU5mYi78UXQX3ddn0',
    appId: '1:235654356599:ios:9a533e67e2684a13d23072',
    messagingSenderId: '235654356599',
    projectId: 'scrappd-4ff5e',
    storageBucket: 'scrappd-4ff5e.firebasestorage.app',
    iosBundleId: 'com.example.scrappdMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKTsOGsx-fjmPCjj_5TCXshJQ68NA7foM',
    appId: '1:235654356599:web:b1420ef93fb847eed23072',
    messagingSenderId: '235654356599',
    projectId: 'scrappd-4ff5e',
    authDomain: 'scrappd-4ff5e.firebaseapp.com',
    storageBucket: 'scrappd-4ff5e.firebasestorage.app',
    measurementId: 'G-PVSL2K4QPP',
  );
}
